USE [STEAM]
GO
CREATE FUNCTION [DBO].[INIDOUTSNAME_ID]
	--JUST LIKE THE NAME ,INPUT ID OUTPUT STEAMGAMENAME 
	
	(@INPUTID VARCHAR(100))
	RETURNS VARCHAR(100)
	BEGIN
		--TO AVOID ERRORS, GENERATE A LOCAL VARIABLE HERE
		DECLARE @X VARCHAR(100)
		
		SELECT @X=SGAMENAME 
		FROM [STEAM].[DBO].[INAMETOSTEAMID]
		WHERE  ID=@INPUTID 
		GROUP BY SGAMENAME
		RETURN (@X)
	END
