USE [STEAM]

CREATE FUNCTION [DBO].[INSNAMEOUTID_SGNAME]
	--INPUT SGNAME OUTPUT ID
	(@INPUTSGAMENAME VARCHAR(100))
	RETURNS VARCHAR(100)
	
	BEGIN	
		RETURN(
			SELECT DISTINCT ID FROM [STEAM].[DBO].[INAMETOSTEAMID]
			WHERE  SGAMENAME=@INPUTSGAMENAME 
			GROUP BY ID
		)
	END
