USE [STEAM]

CREATE FUNCTION [DBO].[INTINTEGER]
	(@X INT)
	RETURNS INT
	--TO DETERMINE THE NUMBER IS GREATER THAN ZERO, THIS FUNCTION HAS SUPPORT IN ORACLE DATA BASE,BUT  SQL SERVER DOES NOT.
BEGIN
	IF @X>0
		RETURN 1
	ELSE
		RETURN 0
	RETURN 0
END
