USE [STEAM]

CREATE FUNCTION [DBO].[SCORE_SCORE,ID]
	(@INPUTSCORE REAL,@INPUTID VARCHAR(100))
	--INPUT SCORE AND ID THEN OUT PUT SCORE 
	--FROM MPROFILE SCORE OR AVG OF MGAMEREVIEW SCORE
	RETURNS REAL
AS
BEGIN	
	DECLARE @OUTPUT INT
	
	IF @INPUTSCORE = 0
		IF (SELECT MSCORE FROM MPROFILE WHERE SGAMENAME = @INPUTID)=0

			RETURN(SELECT AVG(SCORE) FROM MGAMEREVIEW WHERE SGAMENAME = @INPUTID)		
		
		RETURN(SELECT MSCORE FROM MPROFILE WHERE SGAMENAME = @INPUTID)		
			
	RETURN @INPUTSCORE
END