USE [STEAM]
GO
--TO DETERMINE WHETHER THE DATE OF THE HOLIDAY LIST
--1/1~1/2,10/7~10/14,12/20~12/31
--OUTPUT 1 OR 0
CREATE FUNCTION [DBO].[VACATION_DATE]
	(@INPUTDATE DATETIME)	
	RETURNS SMALLINT
BEGIN 
	IF MONTH(@INPUTDATE)=1 AND DAY(@INPUTDATE) BETWEEN 1 AND 2
		RETURN 1
	IF MONTH(@INPUTDATE)=10 AND DAY(@INPUTDATE) BETWEEN 7 AND 14
		RETURN 1
	IF MONTH(@INPUTDATE)=12 AND DAY(@INPUTDATE) BETWEEN 20 AND 31
		RETURN 1
	RETURN 0
END