--THIS IS ALL FUNCTION I NEED TO USE FOR STORED PROCEDURE
--YOU CAN FIND THEM IN Scalar Function DIRECTORY
--WRITE BY LIN,MING-CIAN 

USE [STEAM]
GO

DROP FUNCTION 
	[STEAM].[DBO].[INIDOUTSNAME_ID],
	[STEAM].[DBO].[INAMETOSTEAMID],
	[STEAM].[DBO].[INSNAMEOUTID_SGNAME],
	[STEAM].[DBO].[INTINTEGER],
	[STEAM].[DBO].[SCORE_SCORE,ID],
	[STEAM].[DBO].[VACATION_DATE]	
GO 

--JUST LIKE THE NAME ,INPUT ID OUTPUT STEAMGAMENAME 
CREATE FUNCTION [DBO].[INIDOUTSNAME_ID]
	(@INPUTID VARCHAR(100))
	RETURNS VARCHAR(100)
	
	BEGIN	
		--TO AVOID ERRORS, GENERATE A LOCAL VARIABLE HERE
		DECLARE @X VARCHAR(100)
		
		SELECT @X=SGAMENAME 
		FROM [STEAM].[DBO].[INAMETOSTEAMID]
		WHERE  ID=@INPUTID 
		GROUP BY SGAMENAME
		RETURN (@X)
	END
GO

	
--JUST LIKE THE NAME ,INPUT SGNAME OUTPUT ID
CREATE FUNCTION [DBO].[INSNAMEOUTID_SGNAME]	
	(@INPUTSGAMENAME VARCHAR(100))
	RETURNS VARCHAR(100)	
BEGIN	
	RETURN(
		SELECT DISTINCT ID FROM [STEAM].[DBO].[INAMETOSTEAMID]
		WHERE  SGAMENAME=@INPUTSGAMENAME 
		GROUP BY ID
	)
END
GO

--TO DETERMINE THE NUMBER IS GREATER THAN ZERO, 
--THIS FUNCTION HAS SUPPORT IN ORACLE DATA BASE,BUT SQL SERVER DOES NOT.
CREATE FUNCTION [DBO].[INTINTEGER]
	(@X INT)
	RETURNS INT	
BEGIN
	IF @X>0
		RETURN 1
	ELSE
		RETURN 0
	RETURN 0
END
GO

--INPUT SCORE AND ID THEN OUT PUT SCORE 
--FROM MPROFILE SCORE OR AVG OF MGAMEREVIEW SCORE
CREATE FUNCTION [DBO].[SCORE_SCORE,ID]
	(@INPUTSCORE REAL,@INPUTID VARCHAR(100))	
	RETURNS REAL
AS
BEGIN	
	DECLARE @OUTPUT INT
	
	IF @INPUTSCORE = 0
		IF (SELECT MSCORE FROM MPROFILE WHERE SGAMENAME = @INPUTID)=0
			RETURN(SELECT AVG(SCORE) FROM MGAMEREVIEW WHERE SGAMENAME = @INPUTID)		
		RETURN(SELECT MSCORE FROM MPROFILE WHERE SGAMENAME = @INPUTID)			
	RETURN @INPUTSCORE
END
GO

--TO DETERMINE WHETHER THE DATE OF THE HOLIDAY LIST
--1/1~1/2,10/7~10/14,12/20~12/31
--OUTPUT 1 OR 0
CREATE FUNCTION [DBO].[VACATION_DATE]
	(@INPUTDATE DATETIME)	
	RETURNS SMALLINT
BEGIN 
	IF MONTH(@INPUTDATE)=1 AND DAY(@INPUTDATE) BETWEEN 1 AND 2
		RETURN 1
	IF MONTH(@INPUTDATE)=10 AND DAY(@INPUTDATE) BETWEEN 7 AND 14
		RETURN 1
	IF MONTH(@INPUTDATE)=12 AND DAY(@INPUTDATE) BETWEEN 20 AND 31
		RETURN 1
	RETURN 0
END
