USE [STEAM]
GO

--THIS STORED PROCEDURE ACCESS TO HUGE IPRISE DATA, USE WITH GRAMMAR GENERATES TWO LISTS, THEN MERGE.
CREATE PROC [DBO].[CSATTR]
AS

--PRODUCE A STARTING DATE LIST
WITH TABLE1(SGAMENAME,REALESEDATE)													 
AS(
	--IF YOU DIDN'T WRITE TOP QUERY YOU WILL SEE AN ERROR AS FOLLOWS:
	--UNLESS YOU SPECIFY BOTH TOP, OFFSET OR FOR XML, OTHERWISE THE ORDER BY CLAUSE IN A VIEW,
	--INLINE FUNCTIONS, DERIVED TABLES, SUBQUERIES, AND COMMON TABLE EXPRESSION IN THE VOID.
	SELECT TOP 30000 SGAMENAME ,MIN([DATE]) REALESEDATE  
	FROM [STEAM].[DBO].[IPRICE1]
	WHERE COMPANY='STEAM'
		AND PRICE !=0 
	GROUP BY SGAMENAME
	ORDER BY SGAMENAME  	
),
--DISCOUNT LIST GENERATED DURING THE DAY PLUS THE JUDGMENT DATE.
TABLE2																			
AS(	
	--USE DATEDIFF FUNCTION 
	SELECT TOP 30000 A.SGAMENAME ,[DATE] OFFDATE ,DATEDIFF(DAY,REALESEDATE,A.DATE) DIFFDAYFROMRELAESE  
	FROM [STEAM].[DBO].[IPRICE1] A JOIN TABLE1 B ON A.SGAMENAME=B.SGAMENAME
	WHERE COMPANY='STEAM'
			AND PRICE !=0
			AND STATE = 1 
	ORDER BY SGAMENAME
),
--DISCOUNT DATE CATEGORY JUDGMENT
TABLE3																			
AS(
	SELECT TOP 30000 T.SGAMENAME
	--,T.DIFFDAYFROMRELAESE
	
	--USE CASE EXPRESSION
	,'1~90'=CASE WHEN DIFFDAYFROMRELAESE <=90 AND DIFFDAYFROMRELAESE>1 THEN 1 ELSE 0 END
	,'91~180'=CASE WHEN DIFFDAYFROMRELAESE <=180 AND DIFFDAYFROMRELAESE>91 THEN 1 ELSE 0 END
	,'181~270'=CASE WHEN DIFFDAYFROMRELAESE <=270 AND DIFFDAYFROMRELAESE>181 THEN 1 ELSE 0 END
	,'271~360'=CASE WHEN DIFFDAYFROMRELAESE <=360 AND DIFFDAYFROMRELAESE>271 THEN 1 ELSE 0 END
	,'361~450'=CASE WHEN DIFFDAYFROMRELAESE <=450 AND DIFFDAYFROMRELAESE>361 THEN 1 ELSE 0 END
	,'451~540'=CASE WHEN DIFFDAYFROMRELAESE <=540 AND DIFFDAYFROMRELAESE>451 THEN 1 ELSE 0 END
	,'541~630'=CASE WHEN DIFFDAYFROMRELAESE <=630 AND DIFFDAYFROMRELAESE>541 THEN 1 ELSE 0 END
	,'631~720'=CASE WHEN DIFFDAYFROMRELAESE <=720 AND DIFFDAYFROMRELAESE>631 THEN 1 ELSE 0 END
	,'721~810'=CASE WHEN DIFFDAYFROMRELAESE <=810 AND DIFFDAYFROMRELAESE>721 THEN 1 ELSE 0 END
FROM TABLE2 T 
ORDER BY T.SGAMENAME
)
--USE UNDERLINE TO TEST TABLE3 
--SELECT * FROM TABLE3 ORDER BY SGAMENAME
SELECT SGAMENAME
	[90]=CASE WHEN SUM([1~90]) > 0 THEN 1 ELSE 0 END
    ,[180]=CASE WHEN SUM([91~180]) > 0 THEN 1 ELSE 0 END
    ,[270]=CASE WHEN SUM([181~270]) > 0 THEN 1 ELSE 0 END
    ,[360]=CASE WHEN SUM([271~360]) > 0 THEN 1 ELSE 0 END
    ,[450]=CASE WHEN SUM([361~450]) > 0 THEN 1 ELSE 0 END
    ,[540]=CASE WHEN SUM([451~540]) > 0 THEN 1 ELSE 0 END
    ,[630]=CASE WHEN SUM([541~630]) > 0 THEN 1 ELSE 0 END
    ,[720]=CASE WHEN SUM([631~720]) > 0 THEN 1 ELSE 0 END
    ,[810]=CASE WHEN SUM([721~810]) > 0 THEN 1 ELSE 0 END
	  
	,[GENREACTION]
    ,[ACCOUNTING]
    ,[ACTION]
    ,[ADVENTURE]
    ,[ANIMATIONANDMODELING]
    ,[AUDIOPRODUCTION]
    ,[CASUAL]
    ,[DESIGNANDILLUSTRATION]
    ,[EARLYACCESS]
    ,[EDUCATION]
    ,[FREETOPLAY]
    ,[INDIE]
    ,[MASSIVELYMULTIPLAYER]
    ,[PHOTOEDITING]
    ,[RACING]
    ,[RPG]
    ,[SIMULATION]
    ,[SPORTS]
    ,[STRATEGY]
    ,[UTILITIES]
    ,[VIDEOPRODUCTION]
    ,[WEBPUBLISHING]
    ,[SOFTWARETRAINING]
	  
FROM TABLE3 A   JOIN SGAMETAGTF B ON A.SGAMENAME=DBO.INIDOUTSNAME_ID(B.ID)
GROUP BY A.SGAMENAME 		
	,[GENREACTION]
    ,[ACCOUNTING]
    ,[ACTION]
    ,[ADVENTURE]
    ,[ANIMATIONANDMODELING]
    ,[AUDIOPRODUCTION]
    ,[CASUAL]
    ,[DESIGNANDILLUSTRATION]
    ,[EARLYACCESS]
    ,[EDUCATION]
    ,[FREETOPLAY]
    ,[INDIE]
    ,[MASSIVELYMULTIPLAYER]
    ,[PHOTOEDITING]
    ,[RACING]
    ,[RPG]
    ,[SIMULATION]
    ,[SPORTS]
    ,[STRATEGY]
    ,[UTILITIES]
    ,[VIDEOPRODUCTION]
    ,[WEBPUBLISHING]
    ,[SOFTWARETRAINING]	 
ORDER BY A.SGAMENAME

