USE [STEAM]
GO
--A SIMPLE STORED PROCEDURE INPUT ID, COMPANY, 
--TO OUTPUT THE HISTORICAL PRICE RECORDS FOR THIS GAME.
CREATE PROC [DBO].[GPHISTORY_ID,COM] 
	@INPUTID VARCHAR(100),
	@INPUTCOMPANY VARCHAR(100)
AS	
	IF @INPUTCOMPANY ='*'
		SELECT  DATE,COMPANY,PRICE
		FROM IPRICE
		WHERE SGAMENAME = @INPUTID
		ORDER BY COMPANY,DATE,PRICE
	ELSE
		SELECT  DATE,COMPANY,PRICE
		FROM IPRICE
		WHERE SGAMENAME = @INPUTID AND COMPANY = @INPUTCOMPANY
		ORDER BY COMPANY,DATE,PRICE
	