USE [Steam]
GO
--BECAUSE THIS STORED PROCEDURE ACCESS IPRICE, NOT IMMEDIATELY RETURN A TABLE, 
--THIS STORED PROCEDURE WILL BE CONVERTED INTO OPEN IPRICE DATE FORMAT
CREATE PROC [DBO].[IPLOGICDATE]
AS
SELECT I.SGAMENAME
	  ,I.COMPANY
      ,YEAR(I.DATE) YEAR
	  ,MONTH(I.DATE) MONTH
	  ,DAY(I.DATE) DAY
	  
	  --SUNDAY IS 1 ,SATURDAY IS 7
	  ,DATEPART(WEEKDAY,I.DATE) WEEKNAME 
	  ,DATENAME(WEEKDAY,I.DATE) 
      ,I.PRICE
FROM [STEAM].[DBO].[IPRICE] I