USE [STEAM]
GO
--MERGETABLE WITH SGAMETAGTF,SLANGUAGES,PAMK_1639
CREATE PROC [dbo].[MERGETABLE]
AS
WITH C(ID,PAMA)
AS(
	SELECT M.ID,O.PAMA 
	FROM PAMK_1639 O LEFT JOIN INAMETOSTEAMID M ON O.SGAMNAME=M.SGAMENAME
)
SELECT  C.[ID]

    ,[GENREACTION]
    ,[ACCOUNTING]
    ,[ACTION]
    ,[ADVENTURE]
    ,[ANIMATIONANDMODELING]
    ,[AUDIOPRODUCTION]
    ,[CASUAL]
    ,[DESIGNANDILLUSTRATION]
    ,[EARLYACCESS]
    ,[EDUCATION]
    ,[FREETOPLAY]
    ,[INDIE]
    ,[MASSIVELYMULTIPLAYER]
    ,[PHOTOEDITING]
    ,[RACING]
    ,[RPG]
    ,[SIMULATION]
    ,[SPORTS]
    ,[STRATEGY]
    ,[UTILITIES]
    ,[VIDEOPRODUCTION]
    ,[WEBPUBLISHING]
    ,[SOFTWARETRAINING]
		  
	,[PORTUGUESE]
    ,[GERMAN]
    ,[JAPANESE]
    ,[SPANISH]
    ,[POLISH]
    ,[ARABIC]
    ,[SWEDISH]
    ,[TURKISH]
    ,[ROMANIAN]
    ,[CZECH]
    ,[DUTCH]
    ,[KOREAN]
    ,[PORTUGUESE-BRAZIL]
    ,[DANISH]
    ,[BULGARIAN]
    ,[HUNGARIAN]
    ,[UKRAINIAN]
    ,[FRENCH]
    ,[NORWEGIAN]
    ,[SLOVAKIAN]
    ,[RUSSIAN]
    ,[THAI]
    ,[FINNISH]
    ,[TRADITIONAL CHINESE]
    ,[GREEK]
    ,[SIMPLIFIED CHINESE]
    ,[ENGLISH]
    ,[ITALIAN]
	,C.PAMA 
FROM C  LEFT JOIN SGAMETAGTF T ON C.ID=T.ID
        LEFT JOIN SLANGUAGES L ON C.ID = L.ID
WHERE [GENREACTION] IS NOT NULL AND C.ID IS NOT NULL