--THIS QUERY IS TO OBSERVE THE DIFFERENCE BETWEEN THE CUMULATIVE DISTRIBUTION DATE.
--IF THE RESULT IS OUTPUT TO EXCEL DRAWING, YOU CAN SEE THE DISTRIBUTION OF MOST GAMES DISCOUNT DATE.

--BEGIN TABLE
WITH TABLE1(SGAMENAME,REALESEDATE)
AS(
	SELECT TOP 3000 SGAMENAME ,MIN([DATE]) REALESEDATE  
	FROM [STEAM].[DBO].[IPRICE1]
	WHERE COMPANY='STEAM'
		AND PRICE !=0
		--AND SGAMENAME ='AIRCONFLICTSVIETNAM' 
	GROUP BY SGAMENAME
	ORDER BY SGAMENAME  
),
--DETERMINE THE DATE OF THE TABLE TO JOIN A DISCOUNT DAY FORM
TABLE2
AS(
	SELECT TOP 3000 A.SGAMENAME ,[DATE] OFFDATE ,DATEDIFF(DAY,REALESEDATE,A.DATE) DIFFDAYFROMRELAESE  
	FROM [STEAM].[DBO].[IPRICE1] A JOIN TABLE1 B ON A.SGAMENAME=B.SGAMENAME
	WHERE COMPANY='STEAM'
		AND PRICE !=0
		AND STATE = 1 
	ORDER BY SGAMENAME
)
SELECT DIFFDAYFROMRELAESE ,COUNT(*) COUNT 
FROM TABLE2 
GROUP BY DIFFDAYFROMRELAESE 
ORDER BY DIFFDAYFROMRELAESE