--THIS QUERY AND METHOD FOR TESTING TO DETERMINE WHETHER THE CORRECT DATE OF THE DISCOUNT PERIOD

--BEGIN DATE TABLE
WITH TABLE1(SGAMENAME,REALESEDATE)
AS(
	SELECT TOP 3000 SGAMENAME ,MIN([DATE]) REALESEDATE
	FROM [STEAM].[DBO].[IPRICE1]
	WHERE COMPANY='STEAM'
		AND PRICE !=0
		--AND SGAMENAME ='AIRCONFLICTSVIETNAM'
 	GROUP BY SGAMENAME
	ORDER BY SGAMENAME  
),
--DETERMINE THE DATE OF THE TABLE TO JOIN A DISCOUNT DAY FORM
TABLE2
AS(
	SELECT TOP 3000 A.SGAMENAME ,[DATE] OFFDATE ,DATEDIFF(DAY,REALESEDATE,A.DATE) DIFFDAYFROMRELAESE  
	FROM [STEAM].[DBO].[IPRICE1] A JOIN TABLE1 B ON A.SGAMENAME=B.SGAMENAME
	WHERE COMPANY='STEAM'
		AND PRICE !=0
		AND STATE = 1 
	ORDER BY SGAMENAME
),
--DISCOUNT DATE CATEGORY JUDGMENT
TABLE3
AS(
	SELECT TOP 6000 T.SGAMENAME
		--,T.DIFFDAYFROMRELAESE
		,'1~90'=CASE WHEN DIFFDAYFROMRELAESE <=90 AND DIFFDAYFROMRELAESE>1 THEN 1 ELSE 0 END
		,'91~180'=CASE WHEN DIFFDAYFROMRELAESE <=180 AND DIFFDAYFROMRELAESE>91 THEN 1 ELSE 0 END
		,'181~270'=CASE WHEN DIFFDAYFROMRELAESE <=270 AND DIFFDAYFROMRELAESE>181 THEN 1 ELSE 0 END
		,'271~360'=CASE WHEN DIFFDAYFROMRELAESE <=360 AND DIFFDAYFROMRELAESE>271 THEN 1 ELSE 0 END
		,'361~450'=CASE WHEN DIFFDAYFROMRELAESE <=450 AND DIFFDAYFROMRELAESE>361 THEN 1 ELSE 0 END
		,'451~540'=CASE WHEN DIFFDAYFROMRELAESE <=540 AND DIFFDAYFROMRELAESE>451 THEN 1 ELSE 0 END
		,'541~630'=CASE WHEN DIFFDAYFROMRELAESE <=630 AND DIFFDAYFROMRELAESE>541 THEN 1 ELSE 0 END
		,'631~720'=CASE WHEN DIFFDAYFROMRELAESE <=720 AND DIFFDAYFROMRELAESE>631 THEN 1 ELSE 0 END
		,'721~810'=CASE WHEN DIFFDAYFROMRELAESE <=810 AND DIFFDAYFROMRELAESE>721 THEN 1 ELSE 0 END
	FROM TABLE2 T 
	ORDER BY T.SGAMENAME
)
SELECT *
FROM TABLE3
ORDER BY SGAMENAME